[package]
name = "gossip"
version = "0.3.1-unstable"
description = "A social media client for nostr"
authors = ["Mike Dilger <mike@mikedilger.com>"]
license = "MIT"
repository = "https://github.com/mikedilger/gossip"
homepage = "https://github.com/mikedilger/gossip"
default-run = "gossip"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0"
base64 = "0.13"
dirs = "4.0"
eframe = { version = "0.20", features = [ "dark-light", "persistence" ] }
egui_extras = { version = "0.20", features = [ "svg", "tracing" ] }
futures = "0.3"
futures-util = "0.3"
http = "0.2"
image = "0.24"
lazy_static = "1.4"
nostr-types = { git = "https://github.com/mikedilger/nostr-types" }
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
rusqlite = { version = "0.28", features = ["bundled", "chrono", "serde_json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
textnonce = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio-tungstenite = { version = "0.17", features = [ "rustls-tls-native-roots" ] }
tungstenite = { version = "0.17", features = [ "rustls-tls-native-roots" ] }
zeroize = "1.5"
